kind: pipeline
type: kubernetes
name: drone-kubectl

metadata:
  namespace: drone-github

steps:
- name: publish
  image: plugins/kaniko:1.4.1
  settings:
    dockerfile: Dockerfile
    registry: core.harbor.svc.cluster.eu-west-1:8443
    repo: core.harbor.svc.cluster.eu-west-1:8443/scandiweb-buddy/app
    # Enable auto_atg and disable manual tags once fixed https://github.com/drone/drone-kaniko/pull/36
    # auto_tag: true
    tags: "${DRONE_TAG}"
    username:
      from_secret: registry_bot_username
    password:
      from_secret: registry_bot_password
    skip_tls_verify: true

trigger:
  branch:
    - master
  event:
    - push

---
kind: secret
name: registry_bot_password
get:
  path: kubernetes/data/readymage/drone/config_common
  name: registry_bot_password

---
kind: secret
name: registry_bot_username
get:
  path: kubernetes/data/readymage/drone/config_common
  name: registry_bot_username
