---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scandiweb-buddy-external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::536697258217:role/sw-int-k8s-euw1-prod-ext-secrets-scandiweb-buddy
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ssm-parameter-store-scandiweb-buddy
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: scandiweb-buddy-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scandiweb-buddy-tokens
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: ssm-parameter-store-scandiweb-buddy
    kind: SecretStore
  target:
    name: external-integrations
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /sw-int-k8s-euw1-prod/scandiweb-buddy/secrets
