apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scandiweb-buddy
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - buddytools.scandiweb.com
      secretName: scandiweb-buddy-tls
  defaultBackend:
    service:
      name: scandiweb-buddy
      port:
        number: 80
